### ISSUE TITLE
Acompanhamento no Google Analytics

### ISSUE THREAD

**Issue by satoru4fun** [prefeiturasp/SME-plataforma-curriculo#10]
**A sua funcionalidade resolve um problema?.**
Sim. Conhecer o consumidor.

> If you can’t measure, you can’t manage. Essa frase explica por que mensurar as ações de marketing: se você não pode medi-las, não conseguirá administrá-las. Afinal, você precisa saber qual caminho a estratégia está tomando, para otimizá-la e alcançar os resultados.

**Descreva a solução que você espera**
Monitorar o seu site ou aplicativo e identificar como está o seu desempenho em tráfego, engajamento e conversões, de acordo com as ações do usuário nas páginas.

**Algo a mais?**
Procedimento:

1. Cole o seguinte fragmento imediatamente a seguir à etiqueta <head> em cada página do site.
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-85250794-5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-85250794-5');
</script>
```

**Comment by eomine** [comment]
@ludimila Feito no PR acima.

**Comment by victorsenam** [comment]
Resolvido né? Fechando. :tada:
