### ISSUE TITLE
Tornar os ícones e texto da Home sobre o novo currículo clicáveis

### ISSUE THREAD

**Issue by carlalink** [prefeiturasp/SME-plataforma-curriculo#18]
**Qual a melhoria proposta?**

Os professores no teste tentaram acionar diretamente o conteúdo sobre o currículo, porém não estão linkados diretamente as páginas.

<img width="1019" alt="screen shot 2018-09-19 at 13 10 54" src="https://user-images.githubusercontent.com/16597620/45766284-8cf0fb00-bc0d-11e8-9fff-e5a2caeef0f2.png">

**Descreva a solução que você espera**

Quando clicar no ícone ou título  Objetivos de Desenvolvimento, ir para a página: http://curriculo.prefeitura.sp.gov.br/ods

Quando clicar no ícone ou título da Matriz de Saberes, ir para a página: http://curriculo.prefeitura.sp.gov.br/matriz-de-saberes

Quando clicar no ícone ou título dos Objetivos de Aprendizagem: http://curriculo.prefeitura.sp.gov.br/objetivos-de-aprendizagem

O mesmo vale para os ícones na página do Currículo (você só entra se apertar no botão): http://curriculo.prefeitura.sp.gov.br/curriculo 

**Algo a mais?**
Adicione as informações que julgar necessárias, prints, refêrencias.
--

**Comment by lsfgrd** [comment]
ei! gostaria de ajudar com essa issue :)

**entretanto**, tenho um contraponto: não vejo razão para colocar os ícones na página do Currículo como clicáveis, visto que o botão já está fazendo essa função. se, nesse contexto, os professores também tentaram acessar através dos ícones, talvez o caminho seja repensar os botões (inclusive, não achei eles com muita cara de clicável [acho que seria interessante colocar um background diferente no hover, mas isso é outra história!])

**Comment by carlalink** [comment]
Olá Lais,
Desculpa a demora em responder.

O que a gte percebeu é que o professor que já tiver acessado e quiser
entrar nesse conteúdo precisa fazer muitos cliques ate chegar no conteúdo.

No teste de usabilidade, eles tentaram clicar, pra eles parece que é
clicável, sabe?

A ideia era manter o botão clicável embaixo, mas deixar os outros tb.

O problema de mudar a identidade do botão, é que teria que repensar toda da
plataforma. Dai a decisao tem que ser com a equipe toda.

Beijos

Em Seg, 1 de out de 2018 23:39, Laís Figueiredo <notifications@github.com>
escreveu:

**Comment by thaisfalbo** [comment]
Boa noite, eu já resolvi essa issue, estou aguardando aceitarem meu PR.
https://github.com/prefeiturasp/SME-plataforma-curriculo-interface/pull/70

**Comment by victorsenam** [comment]
O merge foi feito. Fechando a issue. 🎉
