### ISSUE TITLE
Tooltips de filtros com informação fixa

### ISSUE THREAD

**Issue by ludimila** [prefeiturasp/SME-plataforma-curriculo#32]
**Descreva o bug**

Todos os tooltips do filtro tem a mesma informação, o que pode confundir o usuário.

**Para Reproduzir**
Os passos para reproduzir estão abaixo:
1. Navegue até [página das sequências](http://curriculo.prefeitura.sp.gov.br/sequencias)
2. Clique no botão de filtro
4. Escolha um dos filtros 
5. Passe o mouse sobre a interrogação

**O que era para acontecer**
Era para aparecer a informação referente ao filtro selecionado e não a matriz de saberes

**Screenshots**
<img width="1217" alt="captura de tela 2018-11-09 as 12 21 29" src="https://user-images.githubusercontent.com/1562636/48267958-d34b2500-e41a-11e8-83af-9c96636cf0e9.png">

**Comment by pamnovalli** [comment]
Issue solucionada
