### ISSUE TITLE
Incluir uma introdução na busca das Sequências de Atividades

### ISSUE THREAD

**Issue by carlalink** [prefeiturasp/SME-plataforma-curriculo#6]
**Qual a melhoria proposta?.**
Uma descrição clara e precisa da sugestão.

Um texto introdutório para os professores entenderem a proposta da plataforma: de ser um espaço de inspiração, e que ele poderá usar esses conteúdos da forma que achar mais interessante, repensar, recortar, etc. E de alguma forma alinhar a expectativa de que ele não poderá imprimir e levar a atividade diretamente pra aula.

**Descreva a solução que você espera**
Este texto poderia estar presente dentro da Aba Sequências de Atividades, pode ser um texto curto que fica abaixo do título e acima dos filtros.

**Algo a mais?**
Adicione as informações que julgar necessárias, prints, refêrencias.

**Comment by victorsenam** [comment]
Alguma sugestão de texto? Posso colocar o texto lá, mas seria legal que alguém com mais conhecimento sobre a proposta escrevesse ele.

**Comment by ludimila** [comment]
@carlalink @carolsciarotta @campagnucci Temos alguma sugestão de textos?

**Comment by carlalink** [comment]
Gente, desculpa, já fizemos esse na home! pode fechar.
